"""Generate questionnaires.json FROM the validated study pack.

    python build_questionnaires.py

The item text, the IDs, the subscale maps and the reverse-scored items all live in
docs/study-pack/ and were validated there. Retyping them into a second file is how a
questionnaire quietly stops being the instrument it cites -- one wrong word in one
item and the "adapted from IMI" claim in the paper is no longer true.

So the pack stays the source of truth and this generates the machine-readable copy.
Re-run it after editing the pack; `test_questionnaires.py` fails if the two disagree.
"""
import io, json, os, re, sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
PACK = os.path.join(HERE, "..", "docs", "study-pack")
OUT = os.path.join(HERE, "questionnaires.json")

LIKERT_5 = ["Strongly disagree", "Disagree", "Neither agree nor disagree",
            "Agree", "Strongly agree"]

def section(path, heading):
    text = io.open(os.path.join(PACK, path), encoding="utf-8").read()
    start = text.index(heading)
    nxt = text.find("\n## ", start + 1)
    return text[start: nxt if nxt > 0 else len(text)]

def items(path, heading, id_re):
    """Rows shaped `| M1 | statement | ... |` -> [{id, text}]."""
    out = []
    for line in section(path, heading).split("\n"):
        m = re.match(r"\|\s*(" + id_re + r")\s*\|\s*([^|]+?)\s*\|", line)
        if m:
            out.append({"id": m.group(1), "text": m.group(2).strip()})
    return out

def choice_items(path, heading, id_re):
    """Rows shaped `| AGE | Age range | opt1; opt2; ... |` -> [{id, text, options}].

    For the NEW `single` (categorical) item type: unlike `items()`, the table carries a
    third column of ";"-separated options, which is exactly the client's `options` list
    for that item -- so the pack stays the one place the wording AND the choices live.
    ";" rather than "/" on purpose: "Non-binary / other" is itself one option whose text
    contains a slash, so "/" cannot be the list separator without splitting it in two.
    """
    out = []
    for line in section(path, heading).split("\n"):
        m = re.match(r"\|\s*(" + id_re + r")\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|", line)
        if m:
            options = [o.strip() for o in m.group(3).split(";")]
            out.append({"id": m.group(1), "text": m.group(2).strip(),
                        "type": "single", "options": options})
    return out

REVERSE = {"M9", "M11"}          # 06_scoring-codebook-analysis.md §C
SUBSCALES = {
    "imi": {"IE": ["M1", "M5", "M9"], "PC": ["M2", "M6", "M10"],
            "EI": ["M3", "M7", "M11"], "VU": ["M4", "M8", "M12"]},
    "coi": {"TP": ["I1", "I2", "I3", "I4"], "SP": ["I5", "I6", "I7", "I8"]},
    "arcs": {"arcs_s": ["S1", "S2", "S3", "S4", "S5"],
             "arcs_global": ["G1", "G2", "G3"]},
}

bank = {
    "_source": "GENERATED by build_questionnaires.py from docs/study-pack/. Do not "
               "hand-edit: edit the pack and re-run. test_questionnaires.py enforces it.",
    "instruments": {
        "imi": {
            "title": "How the activities felt",
            "cite": "Adapted from the Intrinsic Motivation Inventory "
                    "(McAuley, Duncan & Tammen, 1989).",
            "scale": LIKERT_5, "when": "once, after the study",
            "construct": "H2 motivation",
            "items": items("04_post-questionnaire.md", "## §1", r"M\d+"),
            "reverse": sorted(REVERSE), "subscales": SUBSCALES["imi"],
        },
        "coi": {
            "title": "The game and the tutor as your teacher",
            "cite": "Community of Inquiry, reworded (instructor -> game + AI tutor). "
                    "Non-validated adaptation; exploratory.",
            "scale": LIKERT_5, "when": "once, after the study",
            "construct": "H3 interaction",
            "items": items("04_post-questionnaire.md", "## §2", r"I\d+"),
            "reverse": [], "subscales": SUBSCALES["coi"],
        },
        "arcs": {
            "title": "How satisfied you were",
            "cite": "ARCS-S (Keller). Null result expected and pre-registered as such.",
            "scale": LIKERT_5, "when": "once, after the study",
            "construct": "H4 satisfaction",
            "items": items("04_post-questionnaire.md", "## §3", r"[SG]\d+"),
            "reverse": [], "subscales": SUBSCALES["arcs"],
        },
        "paas": {
            "title": "Mental effort",
            "cite": "Paas (1992) single-item mental-effort scale.",
            # The only 9-point instrument, and the only PER-TOPIC one -- the pack
            # says "immediately after finishing each topic's games and post-quiz".
            "scale": ["very, very low", "very low", "low", "rather low",
                      "neither low nor high", "rather high", "high", "very high",
                      "very, very high"],
            "when": "per topic, at the end of the unit",
            "construct": "cognitive load",
            "items": [{"id": "P1",
                       "text": "How much mental effort did you invest in learning "
                               "this topic?"}],
            "reverse": [], "subscales": {},
        },
        "demographics": {
            "title": "About you",
            "cite": "App-collected subset of docs/study-pack/02_demographics.md (D1, D2, D7, "
                    "D8). Device (D9) is auto-logged server-side, not asked -- see "
                    "questionnaire_api.py / auth_api.py.",
            # No shared scale: AGE is free-typed `text` (Wilson, live: "just let them
            # input" -- a typed age is richer than a 5-way bucket and can always be
            # re-bucketed later; a bucket cannot be un-bucketed). GENDER/GAMING/AITOOL
            # stay `single`, each carrying its own options.
            "scale": [], "when": "once, before the first topic",
            "construct": "descriptive covariate",
            "items": (
                [{**it, "type": "text"} for it in
                 items("02_demographics.md", "## App-collected subset", r"AGE")]
                + choice_items("02_demographics.md", "## App-collected subset",
                               r"GENDER|GAMING|AITOOL")
            ),
            "reverse": [], "subscales": {},
        },
        "feedback": {
            "title": "How this went for you",
            "cite": "Open-ended, app-authored (docs/study-pack/09_app-feedback.md). Not a "
                    "validated instrument -- free-text feedback for the course team.",
            "scale": [], "when": "once, at the end of the study",
            "construct": "open feedback",
            "items": [{**it, "type": "text"} for it in
                      items("09_app-feedback.md", "| ID | Text |", r"FB_[A-Z]+")],
            "reverse": [], "subscales": {},
        },
    },
}

for name, inst in bank["instruments"].items():
    n = len(inst["items"])
    print(f"  {name:6} {n:3} item(s)  scale of {len(inst['scale'])}")
    if not n:
        raise SystemExit(f"FAIL: {name} extracted zero items -- the pack's table shape changed")

io.open(OUT, "w", encoding="utf-8", newline="\n").write(json.dumps(bank, indent=1, ensure_ascii=False) + "\n")
print(f"\nwrote {OUT}")
