"""Generate a topic schedule with dates relative to TODAY, for the browser tests.

    python make_e2e_schedule.py <out.json>

WHY THIS EXISTS. `topic_schedule.json` holds real (currently placeholder) term dates,
so on any given day every topic is `locked` and the end-to-end happy path — sign in,
enter the open topic, walk the unit — cannot run at all. Committing a second schedule
with hard-coded dates would go stale the week after it was written and quietly stop
testing anything.

So the dates are computed from today, and the file this writes is throwaway.

It deliberately produces ALL THREE states at once, because the unhappy paths need them
as much as the happy path needs an open one:

    open    session 5  -> today + 3   (window opened 4 days ago, closes tomorrow)
    late    session 3  -> today - 5   (window closed 3 days ago)
    locked  everything else, pushed far enough out to stay shut

Session 5 is chosen because webers-law and gestalt sit on it and both have an MC item
bank, so the pre/post check steps actually render. Session 3 carries memory and
problem-solving, which also have banks — a late topic that is still enterable.

Run the API against it:

    TOPIC_SCHEDULE_PATH=<out.json> python -m uvicorn rag_api:app --port 8080
"""

import argparse
import json
import os
import sys
from datetime import date, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "topic_schedule.json")

# session number -> days from today for that session's lecture
OFFSETS = {5: 3, 3: -5}
DEFAULT_FAR = 120          # everything else: safely locked


def build(today: date) -> dict:
    with open(SRC, encoding="utf-8") as fh:
        cfg = json.load(fh)

    sections = sorted(cfg["sections"])          # A, B, C on consecutive days
    sessions = {}
    for n in sorted(cfg["sessions"], key=int):
        offset = OFFSETS.get(int(n), DEFAULT_FAR + int(n) * 7)
        base = today + timedelta(days=offset)
        sessions[n] = {s: (base + timedelta(days=i)).isoformat()
                       for i, s in enumerate(sections)}

    cfg["sessions"] = sessions
    cfg["_comment"] = [
        "GENERATED BY make_e2e_schedule.py — do not commit, do not deploy.",
        f"Dates are relative to {today.isoformat()}.",
        "session 5 = open now, session 3 = late, everything else locked.",
    ]
    return cfg


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--today", help="YYYY-MM-DD, for reproducing a specific day")
    args = ap.parse_args()

    today = date.fromisoformat(args.today) if args.today else date.today()
    cfg = build(today)

    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(cfg, fh, indent=2)

    # Report what the API will actually serve, so a failing test can be told apart
    # from a schedule that did not do what this script intended.
    sys.path.insert(0, HERE)
    os.environ["TOPIC_SCHEDULE_PATH"] = os.path.abspath(args.out)
    import schedule
    schedule._config = None                     # drop any cached load
    states = {}
    for st in schedule.topic_states("24000001A", "A"):
        states.setdefault(st["state"], []).append(st["topic_id"])
    print(f"  wrote {args.out}")
    for state in ("open", "late", "locked", "unscheduled"):
        if state in states:
            shown = ", ".join(states[state][:4])
            more = f" (+{len(states[state]) - 4} more)" if len(states[state]) > 4 else ""
            print(f"  {state:<12} {len(states[state]):>2}  {shown}{more}")
    return 0 if states.get("open") else 1


if __name__ == "__main__":
    sys.exit(main())
